### ISSUE TITLE
Bad Request: can't parse entities in message text

### ISSUE THREAD

**Issue by NaruZosa** [ArionMiles/Torrent-Automation#1]
While running the manual script on my already downloaded Mr Robot, I got this message:

`
Execute: telegram.py -t "*Mr. Robot*" -m "_S01E01 - eps1.0_hellofriend.mov_ is ready."
`
`
OK: False
`
`
Error: 400
`
`
Description: Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 44
`
Here's the log for the move command in case it helps

`[MOVE] Rename [C:\Users\Bradl\Downloads\torrents\Mr.Robot.Season.1.720p.BluRay.x264.ShAaNiG\Mr.Robot.S01E01.720p.BluRay.x264.ShAaNiG.mkv] to [C:\Users\Bradl\Downloads\torrents\Mr. Robot\Season 1\S01E01 - eps1.0_hellofriend.mov.mkv]
`

If there's any more details I can provide, please let me know. Once again, thanks for all the help!

**Comment by NaruZosa** [comment]
Okay, I feel stupid now.

Turns out the download wasn't finished, so it had an underscore at the end.


The problem is entirely caused by the user, not the script. Sorry for wasting your time.

**Comment by ArionMiles** [comment]
Actually, the file name is interfering here. The script uses markdown for formatting, and because of your file name containing an underscore, it brings it to a total of 3 underscores. [If you have an odd number of underscores/asterisks in the message, it causes the API to throw this error.](https://github.com/python-telegram-bot/python-telegram-bot/issues/131#issuecomment-167003086)

So you'll have to be careful with Mr.Robot episodes. I love that show, btw.
